### ISSUE TITLE
Error: Cannot find module '@ast-grep/napi-darwin-x64' in version 2.1.0

### ISSUE THREAD

**Issue by laurenmbeatty** [emosheeep/fe-tools#23] opened 2024-05-11 12:28 UTC
I'm updating from `2.0.1` to version `2.1.0`, and I'm running into the error when building:

`Cannot find module '@ast-grep/napi-darwin-x64' in version 2.1.0`

When inspecting what gets installed between the 2.0 and 2.1 I see this:

![Screen Shot 2024-05-11 at 7 22 51 AM](https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/10378331/51030f6e-ab4c-44da-a735-ae412c0c0c09)

![Screen Shot 2024-05-11 at 7 24 01 AM](https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/10378331/de079906-5b46-43e8-94f2-17993cfaa8d4)

This is in the `index.cjs` file from `vite-plugin-lib-inject-css` library.

I wonder if there is something that can be done on `vite-plugin-lib-inject-css`'s end here, or if it is a config issue on my end.

I'm hoping to upgrade to this `2.1` version because it fixes the problem I'm having with `use strict` and the injected css file ending up on the same line.

Thanks so much for your help.

**Comment by emosheeep** [comment] 2024-05-11 13:55
I tested normal before. Could you please provide me a minimal reproduction so I can take a deep look？Thanks so much.

**Comment by laurenmbeatty** [comment] 2024-05-11 16:45
Minimal reproduction [here](https://github.com/laurenmbeatty/inject-lib-css-repro).

**Comment by emosheeep** [comment] 2024-05-12 08:46
<img width="858" alt="image" src="https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/31957758/0b8b5420-d2e6-4158-9327-9cecd05da2de">
I tried to build and succeeded. Seems weird, could you please try to upgrade you version about pnpm or node?

**Comment by emosheeep** [comment] 2024-05-12 10:26
> <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/31957758/329836953-0b8b5420-d2e6-4158-9327-9cecd05da2de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDM4NjcsIm5iZiI6MTcxNTUwMzU2NywicGF0aCI6Ii8zMTk1Nzc1OC8zMjk4MzY5NTMtMGI4YjU0MjAtZDJlNi00MTU4LTkzMjctOWNlY2QwNWRhMmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA4NDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NjFhZmQ5ZTdmZDBhYjg4NjZlZmI2NDA3ZjA5ZWRmNzEyNjE4ZTc0ZTJjMzg1MjVjZDU0MzM5ODBmMmJhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0INN8b0ABgFiK-ddpvgYggrRHMSp2SDdgeXEE7JHHi4">
I tried to build and succeeded. Seems weird, could you please try to upgrade you version about pnpm or node?

**Comment by laurenmbeatty** [comment] 2024-05-12 11:03
What version of pnpm and node are you using, so I can try to match. Thanks!

**Comment by emosheeep** [comment] 2024-05-12 11:05
<img width="213" alt="image" src="https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/31957758/54523863-5596-4a86-803e-2b27ad232a91">

**Comment by laurenmbeatty** [comment] 2024-05-12 12:24
Hmm...still getting the same error. If I downgrade to `2.0.1` it builds. Using `2.1.0` I get the error. I switched to node `21.6.2`, and pnpm `9.0.5`.

![Screen Shot 2024-05-12 at 7 24 05 AM](https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/10378331/ca2f4bf8-d0ee-46d5-8974-1c4c2f3f2c83)


![Screen Shot 2024-05-12 at 7 22 03 AM](https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/10378331/3f4d1f2c-fc01-4db5-823c-b2bf4a84999a)

**Comment by emosheeep** [comment] 2024-05-12 12:27
Did you test on mac or linux？ I guess you're using windows？

**Comment by laurenmbeatty** [comment] 2024-05-12 12:34
I'm on a mac.

**Comment by emosheeep** [comment] 2024-05-12 13:21
Maybe you can try to use a cloud ide to reproduce such as a code sandbox or the other

**Comment by laurenmbeatty** [comment] 2024-05-12 14:07
I went down an `@ast-grep/` rabbit hole. I found this in my `pnpm-lock.yaml` file:

![Screen Shot 2024-05-12 at 9 04 19 AM](https://github.com/emosheeep/vite-plugin-lib-inject-css/assets/10378331/a956e9d9-b8b8-4f0d-b0c7-89b32a1da400)

They no longer have `@ast-grep/napi-darwin-x64`, which is only available in version `20.5`. If I manually add that to my `devDependencies`, then it works. My processor is Intel.

`"@ast-grep/napi-darwin-x64": "0.20.5"`

**Comment by emosheeep** [comment] 2024-05-12 14:14
Wow, you're so careful🎉 that I don't notice it. I don't know if it is a common problem that should be fixed by @ast-grep/napi 🤔, how do you think it🌚, I have no idea because I haven't run into it, is there something I can help with you?

**Comment by laurenmbeatty** [comment] 2024-05-12 14:19
I can open up an MR to pin the version of `@ast-grep/napi` to `0.20.5`, but I'm not sure you'd want that. Let me know. In the meantime, I can open up an issue over on `@ast-grep/napi`.

**Comment by emosheeep** [comment] 2024-05-12 14:23
I prefer the latter because this problem occurs in @ast-grep/napi, maybe the modifications on the origin of the problem should be the permanent way to resolve it 🙏.

**Comment by laurenmbeatty** [comment] 2024-05-12 14:45
Done!

**Comment by emosheeep** [comment] 2024-05-12 14:48
Thanks so much, I'll upgrade it in time when they fix this problem.

**Comment by HerringtonDarkholme** [comment] 2024-05-13 06:28
Hi ast-grep released 0.22.3 that fixed the issue https://www.npmjs.com/package/@ast-grep/napi-darwin-x64

**Comment by emosheeep** [comment] 2024-05-13 06:44
Okay, I'll publish a new version later today.

**Comment by WebAiz** [comment] 2024-05-13 07:19
Hello. good to hear that! I'm have the same issue with this package

**Closed as completed** 2024-05-13 07:36 UTC

**Comment by emosheeep** [comment] 2024-05-13 07:40
v2.1.1 has been published.

**Comment by laurenmbeatty** [comment] 2024-05-13 10:28
Thank you, @emosheeep !
